### ISSUE TITLE
Feedback not collected

### ISSUE THREAD

**Issue by ProjectsOfMLee** [trubrics/streamlit-feedback#2]
```python
def submit_feedback(user_feedback, prompt, response):
    st.toast(f"Feedback submitted ✅")
    user_feedback["datetime"] = datetime.now().isoformat()
    return user_feedback

if "feedback" not in st.session_state:
    st.session_state.feedback = []
    st.session_state.feedback_key = 0

if prompt := st.chat_input("Write your prompt here"):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    full_response = generate_response(prompt=prompt)
    st.markdown(full_response)
    
    st.session_state.feedback_key += 1
    st.session_state.feedback.append(streamlit_feedback(
        feedback_type="faces",
        optional_text_label="[Optional] Please provide an explanation",
        on_submit=submit_feedback,
        kwargs={"prompt": prompt, "response": full_response},
        align="flex-end",
        key=st.session_state.feedback_key,
    ))
    st.session_state.messages.append({"role": "assistant", "content": full_response, "datetime" : datetime.now().isoformat()})
```

I expect this to collect feedback but when I click one of the faces, the st.toast does not appear and the feedback is never collected. However, the front-end components are there to click and textbox will appear for optional feedback. But on click it seems like it suddenly "refreshes" and the feedback faces along with the textbox just disappear, while the prompt and the response is still there and I could prompt it again, same issues happen all over again.

I already tried the simple way without putting the feedback into `st.session_state`, also the same issue, on click the `on_submit` function never really ran

**Comment by ProjectsOfMLee** [comment]
@jeffkayne hi, it would be very helpful if you could look into this as well.

**Comment by jeffkayne** [comment]
This is down to how streamlit components are run. When you click the submit UI button, the whole streamlit app is refreshed, before running the `on_submit` function. From your code snippet, this means that as the app refreshes, the `if prompt := st.chat_input("Write your prompt here"):` statement is no longer valid, and therefore the `streamlit_feedback()` function is not executed, thus neither is the `on_submit` function.

I'm also guessing that this is just half of your code snippet, so I'm not sure exactly what you are trying to achieve. If it is just a regular chatbot with streamlit's chat elements, there are a number of working examples [here](https://github.com/trubrics/streamlit-feedback/blob/main/streamlit_feedback/examples.py). In the `chatbot_thumbs_app()` example, we use an st.experimental_rerun() to re-execute the app after the `if prompt := st.chat_input():`, and then collect feedback for each message above. If these examples don't cover your use case, please paste your whole app code and I'll take a deeper look!

Does this answer your question?
Thanks!

**Comment by ProjectsOfMLee** [comment]
> This is down to how streamlit components are run. When you click the submit UI button, the whole streamlit app is refreshed, before running the `on_submit` function. From your code snippet, this means that as the app refreshes, the `if prompt := st.chat_input("Write your prompt here"):` statement is no longer valid, and therefore the `streamlit_feedback()` function is not executed, thus neither is the `on_submit` function.
> 
> I'm also guessing that this is just half of your code snippet, so I'm not sure exactly what you are trying to achieve. If it is just a regular chatbot with streamlit's chat elements, there are a number of working examples [here](https://github.com/trubrics/streamlit-feedback/blob/main/streamlit_feedback/examples.py). In the `chatbot_thumbs_app()` example, we use an st.experimental_rerun() to re-execute the app after the `if prompt := st.chat_input():`, and then collect feedback for each message above. If these examples don't cover your use case, please paste your whole app code and I'll take a deeper look!
> 
> Does this answer your question? Thanks!

Absolutely. Thank you! I figured the same thing but could not see the component function itself. I got it running now but the feedback faces are persistent on my app, all the faces chosen are displayed like a face-stack at the right corner.

**Comment by jeffkayne** [comment]
Great! What do you mean by face-stack? Please share a screenshot if this is an issue

**Comment by ProjectsOfMLee** [comment]
> Great! What do you mean by face-stack? Please share a screenshot if this is an issue

![image](https://github.com/trubrics/streamlit-feedback/assets/104241750/79c31677-22a6-4a37-98b7-21c72a989b82)

all the feedback faces are stacked together
