### ISSUE TITLE
Why do i have to login on Trubrics?

### ISSUE THREAD

**Issue by kapilw25** [trubrics/streamlit-feedback#27]
"Why is it necessary to log in to Trubrics?"
I don't want to share my sensitive data with Trubrics. 
How can I use all the features [Admin + Analytics UI] of Trubrics
without using any login on Trubrics?

**Comment by jeffkayne** [comment]
We don't have an enterprise license yet available. To use all the features you must log your data to Trubrics for now

**Comment by kapilw25** [comment]
Thanks, Jeff. I shared "Trubrics" with my AI community, and we were curious why it's not famous yet, given its strong potential with LLMs. It turns out the [Admin + Analytics UI] features have a risk of data breach.

Jeff, with the current restrictions, we can't use "Trubrics" for any of our personal research. It needs improvement. Remember, making it open-source is crucial to take Trubrics to public, as seen with projects like Llama and Streamlit.

I discovered Trubrics through your Streamlit talk.
https://www.youtube.com/watch?v=mAbpqL53pPI

Good Work, Jeff!

**Comment by jeffkayne** [comment]
Thanks a lot :)

We will open source select parts of our app for the community (like our [streamlit-feedback](https://github.com/trubrics/streamlit-feedback) component), but open sourcing the main app is not part of our strategy. 

Our SaaS platform is fully secure, mitigating any risk of data breach. Soon we will also be looking to release an enterprise version for self hosting too.
