### ISSUE TITLE
Is there any way to modify the one-line textbox to a multi-line text area?

### ISSUE THREAD

**Issue by Dori-Nilou** [trubrics/streamlit-feedback#28]
The text input box for this component seems to be limited to a single line, so line breaks cannot be entered.
How can I modify it to a multi-line text box?

**Comment by jeffkayne** [comment]
Hello, yes there is a parameter `max_text_length` for multiline feedback. See #9

**Comment by Dori-Nilou** [comment]
Thank you for your reply!
