### ISSUE TITLE
Thumb buttons aren't visible with streamlit==1.32.2

### ISSUE THREAD

**Issue by mariyka314** [trubrics/streamlit-feedback#32]
Hi! I'm building an app and hosting it on the Community Cloud with streamlit==1.32.2. I encountered an issue, that feedback buttons aren't visible while deployed on the Cloud. The difference causing that between my local machine and the Cloud is the streamlit version. So I've updated the local version to be the same as in Cloud (streamlit==1.32.2) and buttons aren't visible. I tried a workaround specifying streamlit==1.32.1 in the requirements, but the Cloud ignores that and doesn't seem to allow to downgrade the streamlit to 1.32.1. so I'm hoping you could help with fixing button visibility for streamlit==1.32.2. Thanks

**Comment by jeffkayne** [comment]
I have tested the component for 1.32.2 and there seems to be no issue on my side
