### ISSUE TITLE
Who is maintaining version 0.1.3?

### ISSUE THREAD

**Issue by skabbit** [trubrics/streamlit-feedback#36]
I found this repo has 0.1.2 version, but in pip it is 0.1.3.

**Comment by jeffkayne** [comment]
just updated this, thanks. the code now matches the version on pypi

**Comment by skabbit** [comment]
Thank you!
Could you also add a development guide? Because it is for sure required to set `_RELEASE = True` at some point to check whether the code is compatible with some app.
