### ISSUE TITLE
Thumps up and downs for the previous message

### ISSUE THREAD

**Issue by preethamam** [trubrics/streamlit-feedback#4]
Is there a way to get thumps up and downs for the previous assistant messages in history?

**Comment by preethamam** [comment]
@jeffkayne yes, like that for previous messages.

**Comment by jeffkayne** [comment]
Please check out the `chatbot_thumbs_app()` example [here](https://github.com/trubrics/streamlit-feedback/blob/main/streamlit_feedback/examples.py)

**Comment by preethamam** [comment]
Thanks, it worked!
